briandelmsft/STAT-Function

tests/test_rest.py, tests/test_stat.py
* Adding MDCA check to Endpoint test case
* Adding test case for file module
=> Adding missing test cases

.github/workflows/stat_function_build.yml
This will add a GitHub action that will build the necessary zip file and upload the ZIP file to a Azure Storage Account in my tenant.
This will allow us to point our own installs at a private version that will automatically update with any new commits.
This workflow will only create builds on the main branch and any branches starting with the word build
=> Build Workflow

modules/base.py, modules/mdca.py, modules/mde.py, modules/version.json
* Fixes #13 
* Fixes #14 
* Fixes #15 
* Fixes #16
=> Regression and Bug Fix in MDE/MDCA + Enhancement in Base

classes/__init__.py, modules/base.py, modules/version.json
=> Base and Related Alerts Module Bug fixes

.github/workflows/pytest.yml, .github/workflows/stat_function_build.yml, tests/test_rest.py, tests/test_stat.py
I have updated our test cases to run automatically when a PR is created to pull into main or test*
The test cases were modified a little to load the test data from Azure Blob storage, which the repo has stored secrets with those paths.
With this all tests cases will be run consistently before a merge
=> STAT Test Automation

shared/rest.py
=> Enhanced error hanling on missing env variables

modules/mde.py, modules/playbook.py, modules/version.json
=> Playbook Module Error Handling

modules/version.json, requirements.txt, shared/rest.py
* Fixes #28 
Documented [here](https://github.com/briandelmsft/SentinelAutomationModules/blob/statv2_preview/Docs/authentication.md)
Zip file [here](https://briandel.blob.core.windows.net/statbuild/build_kv-stat.zip?sv=2021-10-04&st=2023-08-11T13%3A14%3A16Z&se=2023-09-01T13%3A14%3A00Z&sr=b&sp=r&sig=qzR9iTLMSsGY5rxIiZbjRbDeyXISPbA6TOuWWtzeYS0%3D) (Link expires at the end of the month so only use for testing this PR)
=> Add Key Vault Support

.github/workflows/pytest.yml, classes/__init__.py, modules/aadrisks.py, modules/base.py, modules/playbook.py, modules/scoring.py, modules/version.json, shared/data.py, shared/rest.py, tests/test_stat.py
GA Update for STAT v2
- Fixes #46 
- Fixes #50 
- Fixes #53 
- Fixes #27 
- Fixes #32
- Fixes #26
=> STAT v2 GA

tests/test_data.py, tests/test_stat.py
=> Adding additional pytests

modules/aadrisks.py
=> Bug fix for non-default options in AAD Risks module

classes/__init__.py
=> Changed Entra ID Module defaults to not return null

modules/base.py, modules/version.json
=> Base Module comments control fix

modules/kql.py, modules/mde.py, shared/data.py
* Fixes #56 
* Fixes #72 
* Fixes #73
=> Add UserDevices to MDE Module comment output

modules/base.py
=> Workspace ARM ID lookup from Preview to GA API Version

modules/__init__.py, modules/base.py, modules/version.json, shared/data.py, tests/test_data.py
=> Add STAT version to exception messages

classes/__init__.py, debug/__init__.py, debug/debug.py, debug/function.json, modules/base.py, modules/ti.py, modules/version.json, shared/data.py, shared/rest.py, tests/test_data.py
- Fixes #90 
- Fixes #91 
- Fixes #93 
- Fixes #95 
- Fixes #96 
Additionally, this moves some of the direct calls to requests module to the rest module
=> Connection Retry Handling & Debug Module & Optional Enrichment Controls

.github/workflows/stat_function_build.yml
=> Adding debug module to package

modules/scoring.py, modules/version.json
=> Fix for Scoring issue when using new logic apps designer

debug/debug.py, modules/version.json
Related to #108 
Provides the ability to check role assignments in context of the STAT identity
=> Adding RBAC check to debug

debug/debug.py, modules/version.json
Looking for known compatible RBAC roles like Sentinel Contributor, Sentinel Responder, Owner, or Contributor
=> Adding RBAC role check to debug

classes/__init__.py, modules/base.py, modules/version.json
Adds enrichment source info to base module output to make it easier to troubleshoot if an entity fails to resolve, or resolves incorrectly.
Relates to #100
=> Base module - Adding enrichment source info

classes/__init__.py, modules/base.py, modules/version.json
Adding the CurrentVersion of STAT to the output of the base module
Fixes #122
=> Added current STAT version to Base Output

.github/workflows/pytest.yml, debug/debug.py, modules/version.json, shared/data.py, tests/test_data.py
Adds the ability to set a custom datetime format string through the environment variable `DATE_FORMAT`
Adds ability to convert time zone in comments through the `TIME_ZONE` environment variable
- Fixes #127
=> Datetime format and time zone conversion in comments

classes/__init__.py, modules/exchange.py, modules/scoring.py, modules/version.json
=> Adding scoring for Exchange and updating for Entra

modules/scoring.py, modules/version.json
=> Added Privileged account scoring to scoring module

classes/__init__.py, modules/base.py, modules/version.json, shared/data.py, tests/test_stat_kql.py
=> IP Entity handling update

classes/__init__.py, modules/files/exposure-device.kql, modules/files/exposure-user.kql
- Fixing issue when account entity is unresolved
- Fixing issue when account has no UPN and displayed as None
=> Exposure Management - Initial Feedback

classes/__init__.py, modules/exposure_device.py, modules/exposure_user.py, modules/files/exposure-user.kql
Adding SID detection logic and cleaning up the comment for dev exposure
=> Adding SID detection logic

classes/__init__.py, modules/exposure_device.py, modules/kql.py, modules/relatedalerts.py, modules/ti.py, modules/ueba.py, modules/watchlist.py, tests/test_stat_exoposure.py, tests/test_stat_kql.py
Added support for unsynced entities in Related alerts and other modules
TI Module now is transitioned to new ThreatIntelIndicators table
URL entities in TI module now evaluate domains for TI matches as well as full URL matches
=> Unsynced Entity support, TI Module update for new tables
